// React Design System
// Generated by Figma Make

// Theme exports
export { AppThemeProvider } from './theme/AppThemeProvider';
export * from './theme/colorSchemes';
export * from './theme/typography';
export * from './theme/spacing';
export * from './theme/radius';
export * from './theme/elevation';
export * from './theme/breakpoints';
export * from './theme/motion';

// Token exports
export * from './tokens';

// Utility exports
export * from './utils';

// Component exports
export { Button } from './components/Button';
export { Input } from './components/Input';
export { Card } from './components/Card';
export { Text, Heading } from './components/Typography';

// Types
export interface DesignSystemTheme {
  colors: typeof import('./theme/colorSchemes').lightColors;
  typography: typeof import('./theme/typography').typography;
  spacing: typeof import('./theme/spacing').spacing;
  radius: typeof import('./theme/radius').radius;
  elevation: typeof import('./theme/elevation').elevation;
  breakpoints: typeof import('./theme/breakpoints').breakpoints;
  motion: typeof import('./theme/motion').motion;
}
